### PR TITLE
Longest Common Subsequence

### PR DESCRIPTION
**Pull request by sans2001**
Hi
I made a program on finding longest common subsequence using c.
This is also my hacktoberfest pr.
Hope it is upto mark.
Thanks.

### CODE REVIEW

**Comment by soumy47** [comment]
Hey, @sans2001, you just need to print the lcs's length not the sequence. Anyway, good job and print the length of LCS

**Comment by sans2001** [comment]
ok sure thank you for informing.

**Comment by sans2001** [comment]
Hi i updated the program. Kindly check Now.
Thank you.

**Comment by soumy47** [comment]
well done @sans2001

**Pull request merged**
